import type { AssetPack } from '../../engine/contracts/world';

const ROOT = '/assets/fantasy-city/unified-v1/runtime';

export const fantasyCityUnifiedV1Pack: AssetPack = {
  id: 'fantasy-city-unified-v1',
  version: 1,
  compatibility: { provides: ['fantasy', 'urban', 'walled-city', 'night'] },
  style: {
    guide: '/assets/fantasy-city/unified-v1/master-panorama-style-guide.png',
    palette: {
      sky: 0x25152f,
      shadow: 0x211726,
      terracotta: 0x9d4f30,
      sandstone: 0xd4a46f,
      slate: 0x293247,
      teal: 0x235064,
      amber: 0xf0a744,
    },
    outline: { color: 0x21141f, relativeWeight: 0.012 },
    detail: 'medium',
    groundAnchor: 'bottom-center',
  },
  assets: [
    { id: 'city-sky', source: `${ROOT}/sky.png`, metadata: { role: 'sky', opaque: true } },
    { id: 'city-skyline', source: `${ROOT}/distant-skyline-v2.png`, metadata: { role: 'far-background', overlapPx: 2 } },
    { id: 'city-midground', source: `${ROOT}/midground-roofs-v2.png`, metadata: { role: 'mid-background', overlapPx: 2 } },
    { id: 'city-ground', source: `${ROOT}/street.png`, metadata: { role: 'street', tileSize: [1983, 280] } },
    { id: 'gatehouse-art', source: `${ROOT}/gatehouse-v3.png`, metadata: { role: 'landmark' } },
    { id: 'guildhouse-art', source: `${ROOT}/guildhall-v3.png`, metadata: { role: 'architecture' } },
    { id: 'townhouse-art', source: `${ROOT}/townhouse-v3.png`, metadata: { role: 'architecture' } },
    { id: 'bridge-art', source: `${ROOT}/bridge-v3.png`, metadata: { role: 'structure' } },
    { id: 'market-stall-art', source: `${ROOT}/market-stall-v3.png`, metadata: { role: 'street-prop' } },
    { id: 'apothecary-art', source: `${ROOT}/apothecary-v1.png`, metadata: { role: 'architecture', variant: 'apothecary' } },
    { id: 'bakery-art', source: `${ROOT}/bakery-v1.png`, metadata: { role: 'architecture', variant: 'bakery' } },
    { id: 'workshop-art', source: `${ROOT}/workshop-v1.png`, metadata: { role: 'architecture', variant: 'workshop' } },
    { id: 'celestial-temple-art', source: `${ROOT}/celestial-temple-v1.png`, metadata: { role: 'architecture', variant: 'fantasy-temple' } },
    { id: 'civic-archive-art', source: `${ROOT}/civic-archive-v1.png`, metadata: { role: 'architecture', variant: 'civic-archive' } },
    { id: 'merchant-house-art', source: `${ROOT}/merchant-house-v1.png`, metadata: { role: 'architecture', variant: 'merchant-house' } },
    { id: 'tree-cluster-art', source: `${ROOT}/tree-cluster.png`, metadata: { role: 'vegetation' } },
    { id: 'townsperson-1', source: `${ROOT}/townsperson-1.png`, metadata: { role: 'inhabitant', variant: 1 } },
    { id: 'townsperson-2', source: `${ROOT}/townsperson-2.png`, metadata: { role: 'inhabitant', variant: 2 } },
    { id: 'townsperson-3', source: `${ROOT}/townsperson-3.png`, metadata: { role: 'inhabitant', variant: 3 } },
    { id: 'townsperson-4', source: `${ROOT}/townsperson-4.png`, metadata: { role: 'inhabitant', variant: 4 } },
    { id: 'wagon', source: `${ROOT}/wagon.png`, metadata: { role: 'vehicle' } },
    { id: 'wagon-rolling', source: `${ROOT}/wagon-rolling.png`, frameWidth: 360, frameHeight: 203, metadata: { role: 'animated-vehicle', frames: 12, frameRate: 6 } },
    { id: 'city-bat', source: `${ROOT}/bat-flight.png`, frameWidth: 120, frameHeight: 96, metadata: { role: 'ambient-flight', frames: 3 } },
    { id: 'flying-carpet-rider', source: `${ROOT}/flying-carpet-rider-v1.png`, metadata: { role: 'ambient-flight', occupants: 1 } },
  ],
  recipes: [
    { id: 'landmark-gatehouse', asset: 'gatehouse-art', role: 'landmark', anchor: { x: 0.5, y: 1 }, worldHeight: 550, tags: ['architecture', 'grounded'] },
    { id: 'building-guildhall', asset: 'guildhouse-art', role: 'building', anchor: { x: 0.5, y: 1 }, worldHeight: 430, tags: ['architecture', 'grounded'] },
    { id: 'building-townhouse', asset: 'townhouse-art', role: 'building', anchor: { x: 0.5, y: 1 }, worldHeight: 500, tags: ['architecture', 'grounded'] },
    { id: 'building-apothecary', asset: 'apothecary-art', role: 'building', anchor: { x: 0.5, y: 1 }, worldHeight: 621, tags: ['architecture', 'grounded', 'commercial'] },
    { id: 'building-bakery', asset: 'bakery-art', role: 'building', anchor: { x: 0.5, y: 1 }, worldHeight: 370, tags: ['architecture', 'grounded', 'commercial'] },
    { id: 'building-workshop', asset: 'workshop-art', role: 'building', anchor: { x: 0.5, y: 1 }, worldHeight: 419, tags: ['architecture', 'grounded', 'crafts'] },
    { id: 'building-celestial-temple', asset: 'celestial-temple-art', role: 'building', anchor: { x: 0.5, y: 1 }, worldHeight: 521, tags: ['architecture', 'grounded', 'temple'] },
    { id: 'building-civic-archive', asset: 'civic-archive-art', role: 'building', anchor: { x: 0.5, y: 1 }, worldHeight: 585, tags: ['architecture', 'grounded', 'civic'] },
    { id: 'building-merchant-house', asset: 'merchant-house-art', role: 'building', anchor: { x: 0.5, y: 1 }, worldHeight: 558, tags: ['architecture', 'grounded', 'commercial'] },
    { id: 'prop-market-stall', asset: 'market-stall-art', role: 'prop', anchor: { x: 0.5, y: 1 }, worldHeight: 144, tags: ['grounded', 'market'] },
    { id: 'inhabitant-standing', asset: 'townsperson-1', role: 'inhabitant', anchor: { x: 0.5, y: 1 }, worldHeight: 99, tags: ['grounded', 'stationary'] },
    { id: 'traffic-wagon-far', asset: 'wagon-rolling', role: 'traffic', anchor: { x: 0.5, y: 1 }, worldHeight: 138, animation: 'wagon-roll-right', directions: ['left', 'right'], tags: ['grounded', 'street', 'far-lane'] },
    { id: 'traffic-wagon-near', asset: 'wagon-rolling', role: 'traffic', anchor: { x: 0.5, y: 1 }, worldHeight: 166, animation: 'wagon-roll-right', directions: ['left', 'right'], tags: ['grounded', 'street', 'near-lane'] },
    { id: 'ambient-bat', asset: 'city-bat', role: 'ambient-traffic', anchor: { x: 0.5, y: 0.5 }, worldHeight: 72, animation: 'bat-fly-right', directions: ['left', 'right'], angles: ['high', 'level', 'low'], tags: ['airborne', 'nocturnal'] },
    { id: 'ambient-flying-carpet', asset: 'flying-carpet-rider', role: 'ambient-traffic', anchor: { x: 0.5, y: 0.5 }, worldHeight: 87, directions: ['right'], angles: ['level'], tags: ['airborne', 'occupied', 'carpet-route'] },
  ],
};
