import type { AssetPack } from '../../engine/contracts/world';

export const fantasyCityPack: AssetPack = {
  id: 'fantasy-city-architecture',
  requires: ['fantasy-core'],
  compatibility: { provides: ['urban', 'walled-city'], excludes: ['underwater'] },
  assets: [
    { id: 'sky-moon', source: '/assets/fantasy-city/vertical-slice/moon.png', metadata: { role: 'sky', styleFamily: 'hero-townhouse' } },
    { id: 'sky-cloud', source: '/assets/fantasy-city/vertical-slice/clouds.png', metadata: { role: 'sky', styleFamily: 'hero-townhouse' } },
    { id: 'city-bat', source: '/assets/fantasy-city/vertical-slice/bat.png', metadata: { role: 'ambient-sky-traffic', styleFamily: 'hero-townhouse' } },
    { id: 'hero-townhouse-preview', source: '/assets/fantasy-city/hero-townhouse-detail-calibrated-trimmed.png', metadata: { status: 'approval-preview', detailLevel: 'screensaver-distance', anchorPolicy: 'trimmed-alpha-bottom' } },
    { id: 'city-ground', source: '/assets/fantasy-city/vertical-slice/street.png', metadata: { role: 'foreground-street', tileSize: [1024, 240], perspective: 'shallow-top-surface', styleFamily: 'hero-townhouse' } },
    { id: 'city-skyline', source: '/assets/fantasy-city/vertical-slice/skyline.png', metadata: { role: 'distant-city', anchorPolicy: 'trimmed-alpha-bottom', styleFamily: 'hero-townhouse' } },
    { id: 'guildhouse-art', source: '/assets/fantasy-city/vertical-slice/guildhouse.png', metadata: { role: 'architecture', anchorPolicy: 'trimmed-alpha-bottom', styleFamily: 'hero-townhouse' } },
    { id: 'townhouse-art', source: '/assets/fantasy-city/vertical-slice/townhouse.png', metadata: { role: 'architecture', anchorPolicy: 'trimmed-alpha-bottom', styleFamily: 'hero-townhouse' } },
    { id: 'gatehouse-art', source: '/assets/fantasy-city/vertical-slice/gatehouse.png', metadata: { role: 'landmark', anchorPolicy: 'trimmed-alpha-bottom', styleFamily: 'hero-townhouse' } },
    { id: 'market-stall-art', source: '/assets/fantasy-city/vertical-slice/market-stall.png', metadata: { role: 'street-prop', anchorPolicy: 'trimmed-alpha-bottom', styleFamily: 'hero-townhouse' } },
    { id: 'tree-cluster-art', source: '/assets/fantasy-city/vertical-slice/tree-cluster.png', metadata: { role: 'vegetation', anchorPolicy: 'trimmed-alpha-bottom', styleFamily: 'hero-townhouse' } },
    { id: 'bridge-art', source: '/assets/fantasy-city/vertical-slice/bridge.png', metadata: { role: 'structure', anchorPolicy: 'trimmed-alpha-bottom', styleFamily: 'hero-townhouse' } },
    { id: 'townsperson', source: '/assets/fantasy-city/vertical-slice/townspeople.png', metadata: { role: 'ambient-traffic', anchorPolicy: 'trimmed-alpha-bottom', styleFamily: 'hero-townhouse' } },
    { id: 'townsperson-1', source: '/assets/fantasy-city/vertical-slice/townsperson-1.png', metadata: { role: 'ambient-traffic', variant: 1, anchorPolicy: 'trimmed-alpha-bottom', styleFamily: 'hero-townhouse' } },
    { id: 'townsperson-2', source: '/assets/fantasy-city/vertical-slice/townsperson-2.png', metadata: { role: 'ambient-traffic', variant: 2, anchorPolicy: 'trimmed-alpha-bottom', styleFamily: 'hero-townhouse' } },
    { id: 'townsperson-3', source: '/assets/fantasy-city/vertical-slice/townsperson-3.png', metadata: { role: 'ambient-traffic', variant: 3, anchorPolicy: 'trimmed-alpha-bottom', styleFamily: 'hero-townhouse' } },
    { id: 'wagon', source: '/assets/fantasy-city/vertical-slice/wagon.png', metadata: { role: 'ambient-traffic', anchorPolicy: 'trimmed-alpha-bottom', styleFamily: 'hero-townhouse' } },
    { id: 'wagon-rolling', source: '/assets/fantasy-city/vertical-slice/wagon-rolling-v2.png', frameWidth: 300, frameHeight: 212, metadata: { role: 'animated-traffic', frames: 12, degreesPerFrame: 30, anchorPolicy: 'trimmed-alpha-bottom', styleFamily: 'hero-townhouse' } },
    { id: 'stone-wall', primitive: { kind: 'rect', width: 180, height: 180, color: 0x776779, stroke: 0x3e3348 } },
    { id: 'house-wide', primitive: { kind: 'rect', width: 190, height: 190, color: 0xa45f58, stroke: 0x3d2935, radius: 6 } },
    { id: 'house-tall', primitive: { kind: 'rect', width: 120, height: 260, color: 0x675277, stroke: 0x33263c, radius: 6 } },
    { id: 'roof-wide', primitive: { kind: 'polygon', points: [0, 70, 105, 0, 210, 70], color: 0x49344d, stroke: 0x2d2235 } },
    { id: 'roof-tall', primitive: { kind: 'polygon', points: [0, 90, 70, 0, 140, 90], color: 0x342c49, stroke: 0x211d34 } },
    { id: 'tower', primitive: { kind: 'rect', width: 150, height: 390, color: 0x71657b, stroke: 0x302b3e } },
    { id: 'spire', primitive: { kind: 'polygon', points: [0, 135, 82, 0, 164, 135], color: 0x3d3151, stroke: 0x211d34 } },
    { id: 'city-gate', primitive: { kind: 'rect', width: 270, height: 310, color: 0x695d70, stroke: 0x302a39, radius: 38 } },
    { id: 'window', primitive: { kind: 'rect', width: 22, height: 34, color: 0xf8bd68, stroke: 0x4b3240, radius: 8 } },
    { id: 'market-awning', primitive: { kind: 'polygon', points: [0, 0, 135, 0, 118, 48, 15, 48], color: 0xc47c58, stroke: 0x512f3f } },
    { id: 'fountain', primitive: { kind: 'ellipse', width: 155, height: 42, color: 0x5f8190, stroke: 0x312f43 } },
    { id: 'bridge', primitive: { kind: 'rect', width: 520, height: 90, color: 0x79697a, stroke: 0x3b3240, radius: 42 } },
    { id: 'river', primitive: { kind: 'rect', width: 560, height: 150, color: 0x38576d } },
  ],
};
