import type { WorldTemplate } from '../../../engine/contracts/world';

const VIEW_HEIGHT = window.innerHeight;
const GROUND_Y = VIEW_HEIGHT - 22;
const STREET_Y = VIEW_HEIGHT - 10;

export const coruscantCity: WorldTemplate = {
  id: 'coruscant-city',
  name: 'Coruscant City',
  version: 1,
  designProfile: 'illustrated-cinematic',
  layout: { id: 'elevated-metropolis', tags: ['urban', 'aerial-city', 'platform'], groundY: GROUND_Y, chunkHeight: 1080 },
  camera: { autoScrollSpeed: 30, inputSpeed: 340 },
  themes: ['science-fiction', 'blue-hour'],
  assetPacks: ['coruscant-v1'],
  palette: { sky: 0x101f61, ground: 0x080b24, highlight: 0xffb45c },
  backgrounds: [
    { id: 'coruscant-sky-layer', asset: 'coruscant-sky', depth: -140, parallax: 0.01, y: VIEW_HEIGHT / 2, spacing: 1983, scale: { min: 1, max: 1 } },
    { id: 'coruscant-far-layer', asset: 'coruscant-far-skyline', depth: -120, parallax: 0.04, y: VIEW_HEIGHT * 0.33 + 78, spacing: 1983, scale: { min: 1, max: 1 } },
    { id: 'coruscant-far-base-layer', asset: 'coruscant-far-skyline-base', depth: -110, parallax: 0.07, y: GROUND_Y - 85, spacing: 1983, scale: { min: 1, max: 1 } },
    { id: 'coruscant-mid-layer', asset: 'coruscant-mid-city', depth: -100, parallax: 0.11, y: GROUND_Y - 361.5, spacing: 1983, scale: { min: 1, max: 1 } },
    { id: 'coruscant-platform-layer', asset: 'coruscant-transit-street-band', depth: 0, parallax: 1, y: VIEW_HEIGHT - 55, spacing: 1983, scale: { min: 1, max: 1 } },
  ],
  entities: [
    { id: 'council-rotunda', asset: 'coruscant-council-rotunda', depth: 5, scale: 0.75, anchor: { x: 0.5, y: 1 } },
    { id: 'residential-needle', asset: 'coruscant-residential-needle', depth: 6, scale: 0.65, anchor: { x: 0.5, y: 1 } },
    { id: 'transit-exchange', asset: 'coruscant-transit-exchange', depth: 6, scale: 0.65, anchor: { x: 0.5, y: 1 } },
    { id: 'garden-residence', asset: 'coruscant-garden-residence', depth: 6, scale: 0.6, anchor: { x: 0.5, y: 1 } },
    { id: 'data-archive', asset: 'coruscant-data-archive', depth: 6, scale: 0.6, anchor: { x: 0.5, y: 1 } },
    { id: 'diplomatic-cylinder', asset: 'coruscant-diplomatic-cylinder', depth: 6, scale: 0.6, anchor: { x: 0.5, y: 1 } },
    { id: 'hotel-crown', asset: 'coruscant-hotel-crown', depth: 6, scale: 0.65, anchor: { x: 0.5, y: 1 } },
    { id: 'utility-megablock', asset: 'coruscant-utility-megablock', depth: 6, scale: 0.6, anchor: { x: 0.5, y: 1 } },

    { id: 'civilian', asset: 'coruscant-civilian', depth: 16, scale: 0.42, anchor: { x: 0.5, y: 1 }, components: { tags: ['inhabitant', 'grounded', 'stationary'] } },
    { id: 'technician', asset: 'coruscant-technician', depth: 16, scale: 0.42, anchor: { x: 0.5, y: 1 }, components: { tags: ['inhabitant', 'grounded', 'stationary'] } },
    { id: 'alien-diplomat', asset: 'coruscant-alien-diplomat', depth: 16, scale: 0.42, anchor: { x: 0.5, y: 1 }, components: { tags: ['inhabitant', 'grounded', 'stationary'] } },
    { id: 'service-droid', asset: 'coruscant-service-droid', depth: 16, scale: 0.38, anchor: { x: 0.5, y: 1 }, components: { tags: ['inhabitant', 'grounded', 'stationary'] } },
    { id: 'protocol-android', asset: 'coruscant-protocol-android', depth: 16, scale: 0.44, anchor: { x: 0.5, y: 1 }, components: { tags: ['inhabitant', 'grounded', 'stationary'] } },
    { id: 'armored-patrol', asset: 'coruscant-armored-patrol', depth: 30, scale: 0.45, anchor: { x: 0.5, y: 1 }, components: { tags: ['inhabitant', 'grounded', 'stationary', 'street', 'group'] } },
    { id: 'info-kiosk', asset: 'coruscant-info-kiosk', depth: 14, scale: 0.6, anchor: { x: 0.5, y: 1 } },
    { id: 'alien-planter', asset: 'coruscant-alien-planter', depth: 14, scale: 0.54, anchor: { x: 0.5, y: 1 } },
    { id: 'lane-beacon', asset: 'coruscant-lane-beacon', depth: 14, scale: 0.54, anchor: { x: 0.5, y: 1 } },

    { id: 'distant-speeder-right', asset: 'coruscant-commuter-speeder', depth: -105, scale: 0.13, anchor: { x: 0.5, y: 0.5 }, components: { pathFollower: { path: 'distant-lane-a', speed: { min: 70, max: 125 }, direction: 1 }, tags: ['traffic', 'airborne', 'distant'] } },
    { id: 'distant-speeder-left', asset: 'coruscant-commuter-speeder', depth: -105, scale: 0.11, anchor: { x: 0.5, y: 0.5 }, components: { pathFollower: { path: 'distant-lane-a', speed: { min: 82, max: 138 }, direction: -1 }, tags: ['traffic', 'airborne', 'distant'] } },
    { id: 'distant-shuttle-right', asset: 'coruscant-passenger-shuttle', depth: -104, scale: 0.11, anchor: { x: 0.5, y: 0.5 }, components: { pathFollower: { path: 'distant-lane-b', speed: { min: 48, max: 82 }, direction: 1 }, tags: ['traffic', 'airborne', 'distant', 'transit'] } },
    { id: 'distant-shuttle-left', asset: 'coruscant-passenger-shuttle', depth: -104, scale: 0.12, anchor: { x: 0.5, y: 0.5 }, components: { pathFollower: { path: 'distant-lane-b', speed: { min: 52, max: 88 }, direction: -1 }, tags: ['traffic', 'airborne', 'distant', 'transit'] } },
    { id: 'distant-drone-right', asset: 'coruscant-maintenance-drone', depth: -103, scale: 0.16, anchor: { x: 0.5, y: 0.5 }, components: { pathFollower: { path: 'distant-lane-c', speed: { min: 34, max: 62 }, direction: 1 }, tags: ['traffic', 'airborne', 'distant', 'service'] } },
    { id: 'distant-drone-left', asset: 'coruscant-maintenance-drone', depth: -103, scale: 0.14, anchor: { x: 0.5, y: 0.5 }, components: { pathFollower: { path: 'distant-lane-c', speed: { min: 38, max: 68 }, direction: -1 }, tags: ['traffic', 'airborne', 'distant', 'service'] } },

    { id: 'rolling-astromech', asset: 'coruscant-astromech-droid', depth: 31, scale: 0.4, anchor: { x: 0.5, y: 1 }, components: { pathFollower: { path: 'street-route', speed: { min: 58, max: 68 }, direction: 1 }, tags: ['traffic', 'grounded', 'street', 'tools-stowed'] } },
    { id: 'commuter-speeder-right', asset: 'coruscant-commuter-speeder', depth: -32, scale: 0.54, anchor: { x: 0.5, y: 0.5 }, components: { pathFollower: { path: 'low-air-route', speed: { min: 120, max: 155 }, direction: 1 }, tags: ['traffic', 'airborne', 'civilian'] } },
    { id: 'passenger-shuttle-left', asset: 'coruscant-passenger-shuttle', depth: -45, scale: 0.48, anchor: { x: 0.5, y: 0.5 }, components: { pathFollower: { path: 'mid-air-route', speed: { min: 78, max: 96 }, direction: -1 }, tags: ['traffic', 'airborne', 'transit'] } },
    { id: 'maintenance-drone-right', asset: 'coruscant-maintenance-drone', depth: -28, scale: 0.54, anchor: { x: 0.5, y: 0.5 }, components: { pathFollower: { path: 'service-air-route', speed: { min: 52, max: 66 }, direction: 1 }, tags: ['traffic', 'airborne', 'maintenance'] } },
    { id: 'twin-wing-interceptor-left', asset: 'coruscant-twin-wing-interceptor', depth: -76, scale: 0.34, anchor: { x: 0.5, y: 0.5 }, components: { pathFollower: { path: 'high-air-route', speed: { min: 210, max: 260 }, direction: -1 }, tags: ['traffic', 'airborne', 'rare'] } },
    { id: 'cross-wing-starfighter-right', asset: 'coruscant-cross-wing-starfighter', depth: -74, scale: 0.32, anchor: { x: 0.5, y: 0.5 }, components: { pathFollower: { path: 'high-air-route', speed: { min: 220, max: 275 }, direction: 1 }, tags: ['traffic', 'airborne', 'rare'] } },
  ],
  animations: [],
  chunks: [
    { id: 'council-quarter', width: 690, tags: ['civic', 'landmark'], objects: [{ entity: 'council-rotunda', x: 337, y: GROUND_Y }, { entity: 'info-kiosk', x: 620, y: GROUND_Y }] },
    { id: 'needle-block', width: 190, tags: ['residential'], objects: [{ entity: 'residential-needle', x: 95, y: GROUND_Y }], spawns: [{ entity: 'civilian', count: { min: 1, max: 1 }, area: { x: { min: 150, max: 168 }, y: { min: GROUND_Y, max: GROUND_Y } } }] },
    { id: 'transit-block', width: 610, tags: ['transit'], objects: [{ entity: 'transit-exchange', x: 302, y: GROUND_Y }, { entity: 'lane-beacon', x: 560, y: GROUND_Y }], spawns: [{ entity: 'technician', count: { min: 1, max: 1 }, area: { x: { min: 72, max: 100 }, y: { min: GROUND_Y, max: GROUND_Y } } }] },
    { id: 'garden-block', width: 420, tags: ['residential', 'garden'], objects: [{ entity: 'garden-residence', x: 210, y: GROUND_Y }, { entity: 'alien-planter', x: 362, y: GROUND_Y }] },
    { id: 'archive-block', width: 468, tags: ['data'], objects: [{ entity: 'data-archive', x: 234, y: GROUND_Y }], spawns: [{ entity: 'service-droid', count: { min: 1, max: 1 }, area: { x: { min: 392, max: 418 }, y: { min: GROUND_Y, max: GROUND_Y } } }] },
    { id: 'diplomatic-block', width: 398, tags: ['diplomatic'], objects: [{ entity: 'diplomatic-cylinder', x: 199, y: GROUND_Y }], spawns: [{ entity: 'alien-diplomat', count: { min: 1, max: 1 }, area: { x: { min: 330, max: 354 }, y: { min: GROUND_Y, max: GROUND_Y } } }] },
    { id: 'hotel-block', width: 302, tags: ['hospitality'], objects: [{ entity: 'hotel-crown', x: 151, y: GROUND_Y }], spawns: [{ entity: 'protocol-android', count: { min: 1, max: 1 }, area: { x: { min: 256, max: 274 }, y: { min: GROUND_Y, max: GROUND_Y } } }] },
    { id: 'utility-block', width: 360, tags: ['utility', 'security'], objects: [{ entity: 'utility-megablock', x: 180, y: GROUND_Y }], spawns: [{ entity: 'armored-patrol', count: { min: 1, max: 1 }, area: { x: { min: 300, max: 326 }, y: { min: STREET_Y, max: STREET_Y } } }] },
  ],
  chunkPlan: { mode: 'authored', sequence: ['council-quarter', 'needle-block', 'transit-block', 'garden-block', 'archive-block', 'diplomatic-block', 'hotel-block', 'utility-block'], repeat: true },
  paths: [
    { id: 'distant-lane-a', y: VIEW_HEIGHT * 0.2, xPadding: 80 },
    { id: 'distant-lane-b', y: VIEW_HEIGHT * 0.28, xPadding: 100 },
    { id: 'distant-lane-c', y: VIEW_HEIGHT * 0.36, xPadding: 70 },
    { id: 'distant-lane-d', y: VIEW_HEIGHT * 0.44, xPadding: 110 },
    { id: 'distant-lane-e', y: VIEW_HEIGHT * 0.52, xPadding: 90 },
    { id: 'street-route', y: STREET_Y, xPadding: 100 },
    { id: 'low-air-route', y: 470, xPadding: 220 },
    { id: 'service-air-route', y: 390, xPadding: 130 },
    { id: 'mid-air-route', y: 285, xPadding: 220 },
    { id: 'high-air-route', y: 135, xPadding: 180 },
  ],
  traffic: [
    { id: 'distant-traffic-a', path: 'distant-lane-a', entities: ['distant-speeder-right', 'distant-shuttle-left', 'distant-drone-right'], intervalMs: { min: 900, max: 2600 }, initialDelayMs: { min: 100, max: 1700 }, maxActive: 3, maxActivePerDirection: 2 },
    { id: 'distant-traffic-b', path: 'distant-lane-b', entities: ['distant-speeder-left', 'distant-shuttle-right', 'distant-drone-left'], intervalMs: { min: 1200, max: 3300 }, initialDelayMs: { min: 500, max: 2400 }, maxActive: 3, maxActivePerDirection: 2 },
    { id: 'distant-traffic-c', path: 'distant-lane-c', entities: ['distant-speeder-right', 'distant-speeder-left', 'distant-shuttle-left'], intervalMs: { min: 800, max: 2900 }, initialDelayMs: { min: 0, max: 2100 }, maxActive: 3, maxActivePerDirection: 2 },
    { id: 'distant-traffic-d', path: 'distant-lane-d', entities: ['distant-shuttle-right', 'distant-speeder-left', 'distant-drone-right'], intervalMs: { min: 1500, max: 3900 }, initialDelayMs: { min: 800, max: 3100 }, maxActive: 2, maxActivePerDirection: 2 },
    { id: 'distant-traffic-e', path: 'distant-lane-e', entities: ['distant-drone-left', 'distant-speeder-right', 'distant-shuttle-left'], intervalMs: { min: 1100, max: 3500 }, initialDelayMs: { min: 250, max: 2600 }, maxActive: 2, maxActivePerDirection: 2 },
    { id: 'street-droids', path: 'street-route', entities: ['rolling-astromech'], intervalMs: { min: 15000, max: 22000 }, maxActive: 1, maxActivePerDirection: 1 },
    { id: 'low-speeders', path: 'low-air-route', entities: ['commuter-speeder-right'], intervalMs: { min: 9000, max: 14000 }, maxActive: 1, maxActivePerDirection: 1 },
    { id: 'maintenance-flight', path: 'service-air-route', entities: ['maintenance-drone-right'], intervalMs: { min: 13000, max: 19000 }, maxActive: 1, maxActivePerDirection: 1 },
    { id: 'mid-shuttles', path: 'mid-air-route', entities: ['passenger-shuttle-left'], intervalMs: { min: 12000, max: 18000 }, maxActive: 1, maxActivePerDirection: 1 },
    { id: 'rare-high-flyby', path: 'high-air-route', entities: ['twin-wing-interceptor-left', 'cross-wing-starfighter-right'], intervalMs: { min: 26000, max: 42000 }, maxActive: 1, maxActivePerDirection: 1 },
  ],
  clock: { startHour: 19, realSecondsPerWorldHour: 45, loopHours: 24 },
  environments: [{ id: 'blue-hour', sky: [0x101f61, 0x49428e], ambientTint: 0xffffff }],
  initialEnvironment: 'blue-hour',
  weather: [{ id: 'clear' }],
  initialWeather: 'clear',
  events: [],
  triggers: [],
  pools: [
    { id: 'distant-speeder-right-pool', entity: 'distant-speeder-right', initialSize: 2, maxSize: 4 },
    { id: 'distant-speeder-left-pool', entity: 'distant-speeder-left', initialSize: 2, maxSize: 4 },
    { id: 'distant-shuttle-right-pool', entity: 'distant-shuttle-right', initialSize: 2, maxSize: 4 },
    { id: 'distant-shuttle-left-pool', entity: 'distant-shuttle-left', initialSize: 2, maxSize: 4 },
    { id: 'distant-drone-right-pool', entity: 'distant-drone-right', initialSize: 2, maxSize: 4 },
    { id: 'distant-drone-left-pool', entity: 'distant-drone-left', initialSize: 2, maxSize: 4 },
    { id: 'rolling-astromech-pool', entity: 'rolling-astromech', initialSize: 1, maxSize: 1 },
    { id: 'commuter-speeder-pool', entity: 'commuter-speeder-right', initialSize: 1, maxSize: 1 },
    { id: 'passenger-shuttle-pool', entity: 'passenger-shuttle-left', initialSize: 1, maxSize: 1 },
    { id: 'maintenance-drone-pool', entity: 'maintenance-drone-right', initialSize: 1, maxSize: 1 },
    { id: 'twin-wing-interceptor-pool', entity: 'twin-wing-interceptor-left', initialSize: 1, maxSize: 1 },
    { id: 'cross-wing-starfighter-pool', entity: 'cross-wing-starfighter-right', initialSize: 1, maxSize: 1 },
  ],
  offscreen: { sleepMargin: 260, suspendAnimation: true, suspendParticles: true, keepLogicalTime: true },
  performanceBudget: { targetFps: 60, maxDrawCalls: 250, maxTriangles: 12000, maxTextureMemoryMb: 384, maxActiveEntities: 220, targetResolutions: [[1920, 1080], [2560, 1440], [3840, 2160]] },
  metadata: { description: 'Authored elevated science-fiction metropolis using the Coruscant v1 pack.', styleGuide: '/assets/coruscant/v1/master-panorama-style-guide.png' },
};
